public class KeyCodes
{
    public static readonly string[] keys = {
        "tab",
        "return",
        "pause",
        "escape",
        "space",
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "q",
        "r",
        "s",
        "t",
        "u",
        "v",
        "w",
        "x",
        "y",
        "z",
        "right shift",
        "left shift",
        "right ctrl",
        "left ctrl",
        "right alt",
        "left alt"
    };
}
